class ActionCode:
    MELEE_SUCCESS = "MELEE_SUCCESS"
    SPELL_SUCCESS = "SPELL_SUCCESS"
    MELEE_CRIT = "MELEE_CRIT"
    SPELL_CRIT = "SPELL_CRIT"
    TOO_FAR = "TOO_FAR"
    PARRY = "PARRY"
    DODGE = "DODGE"
    BLOCK = "BLOCK"

