class MessageCode:
    ALL_PLAYER_POS_UPDATE = "ALL_PLAYER_POS_UPDATE"
    PLAYER_POS_UPDATE = "PLAYER_POS_UPDATE"
    PLAYER_UPDATE_INFO = "PLAYER_UPDATE_INFO"
    NEW_PLAYER = "NEW_PLAYER"
    CHECK_CURRENT_PLAYERS = "CHECK_CURRENT_PLAYERS"
    INFO_CHECK_PASSED = "INFO_CHECK_PASSED"
    UDP_PORT_UPDATE = "UDP_PORT_UPDATE"
