class MessageCode:
    PLAYERS_POSITIONS = 'PLAYER_POSITIONS'
    PLAYER_UPDATE = 'PLAYER_UPDATE'
    PLAYER_UPDATE_INFO = 'PLAYER_UPDATE_INFO'
    NEW_PLAYER = 'NEW_PLAYER'
    CHECK_CURRENT_PLAYERS = 'CHECK_CURRENT_PLAYERS'
